title:              Bündnis gegen Antisemitismus Lübeck
email:              BgA-Luebeck@t-online.de
description:        Homepage des Bündnis gegen Antisemitismus Lübeck
author:             BgA-Lübeck
baseurl:            ""
url:                "https://bga-luebeck.github.io"

# Social Profiles
twitter_username:
github_username: bga-luebeck
facebook_username: Bündnis-gegen-Antisemitismus-Lübeck-61556415029043
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Navigation Links
navbar-links:
  Startseite: "/"         # Links to your homepage (index.html)
  Über Uns: "about"      # Links to about.md (Rename if needed)
  Beiträge: "posts"     # If you create a page listing posts at /posts.html or /posts.md
  Kontakt: "contact"    # Links to contact.md (Rename if needed)
