title:              Bündnis gegen Antisemitismus Lübeck
email:              BgA-Luebeck@t-online.de
description:        Gegen jeden Antisemitismus - immer und überall!
author:             BgA-Lübeck
baseurl:            ""
url:                "https://bga-luebeck.de"

# Social Profiles
twitter_username:
github_username:
facebook_username: Bündnis-gegen-Antisemitismus-Lübeck-61556415029043
instagram_username: bga_luebeck
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# build posts that lie in the future
# future: true
